type Query {
    # Dummy query to satisfy the GraphQL requirement. You can replace this later with a real query.
    hello: String
}

type Mutation {

    register(
        input: RegisterInput!
    ): AuthResponse

    login(
        email: String!
        password: String!
    ): AuthResponse

}

type AuthResponse {
    token: String
    user: User
}

type User {
    id: ID
    firstname: String
    lastname: String
    email: String
}

input RegisterInput {
    firstname: String!
    lastname: String!
    email: String!
    password: String!
}
